# Generated by Django 5.2 on 2025-04-22 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
    ]
