# Generated by Django 5.2 on 2025-04-22 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20250422_0453'),
    ]

    operations = [
    ]
