# Generated by Django 5.2 on 2025-04-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_juego_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='imagen',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
