# Generated by Django 5.2 on 2025-04-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_juego_imagen'),
        ('tienda', '0004_auto_20250422_0455'),
    ]

    operations = [
    ]
