# Generated by Django 5.2 on 2025-04-23 19:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_merge_0004_alter_juego_imagen_0004_auto_20250422_0455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='updated_at',
            new_name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='created_at',
        ),
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('juego', 'Juego'), ('consola', 'Consola'), ('accesorio', 'Accesorio')], default='juego', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('accion', 'Acción'), ('aventura', 'Aventura'), ('rpg', 'RPG'), ('estrategia', 'Estrategia'), ('deportes', 'Deportes'), ('simulacion', 'Simulación')], default='accion', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
